### ISSUE TITLE
Qu'utilisez-vous à la place ?

### ISSUE THREAD

**Issue by GautierT** [sgmap/cerfa-form-filler#1]
Bonjour,
Pourquoi cet outil est-il deprecated ? Qu'utilisez-vous à la place ? Il y a t'il des façons aujourd'hui de remplir des cerfa (et donc des PDF) avec un langage informatique ?

Merci.

**Comment by MattiSG** [comment]
Bonjour @GautierT !

Cet outil est déprécié car il a été construit rapidement, n'est pas testé ni documenté correctement, se repose sur une stack exotique par rapport à nos autres outils, et avait en conséquence un coût de maintenance trop élevée par rapport à la valeur fournie.

Nous n'utilisons pas de remplacement en tant que tel. Seule Mes Aides utilisait cet outil, et nous avons simplement supprimé la fonctionnalité associée, car nous n'avions pas les ressources nécessaires pour en assurer la qualité (i.e. maintenir à jour tous les formulaires et les coordonnées `x, y` de chacun des champs).

Pour ce qui est des moyens alternatifs de remplir un Cerfa, il faut comprendre qu'il y a une disjonction majeure entre deux cas.
Si le formulaire est un PDF remplissable, je te conseille l'[excellent tutorial](https://github.com/18F/pdf-forms-tutorial) de @18F sur le sujet. Si tu n'as pas besoin de construire une interface spécifique, tu peux également jeter un œil au service hébergé https://www.formulaires.modernisation.gouv.fr/.
Malheureusement, un nombre encore conséquent de Cerfa n'est mis à disposition que sous la forme de PDF non remplissables, voire scannés. Dans ces cas-là, il faut indiquer des coordonnées `x, y` pour chacun des champs, comme ce dépôt le proposait à l'origine.

En espérant avoir répondu à ta question,
Matti

**Comment by GautierT** [comment]
Merci beaucoup @MattiSG pour ta réponse. J'avais effectivement vu dans le code cette solution de mapper le cerfa suivant des coordonnées x,y. 
Merci pour le lien vers le tutorial. Je vais regarder ça. 
Mais j'avais quelques problèmes avec pdftk sur certains pdf généré avec Adbobe LiveCycle...

Je suis de près vos travaux sur le github sgmap et sur beta.gouv.fr et c'est top de voir que les choses bougent ! 

Bon courage !

Gautier.

**Comment by GautierT** [comment]
@MattiSG : Par contre sur le lien https://www.formulaires.modernisation.gouv.fr/gf/bienvenue.do que suis-je censé trouver ? On me demande un numéro de télédossier et un mdp.

**Comment by MattiSG** [comment]
Pardon, je n'avais pas remarqué que la racine redirigeait vers `/bienvenue`. Il faut plutôt utiliser https://www.formulaires.modernisation.gouv.fr/gf/recherche.do.

Tu peux accéder à quasiment tous les Cerfa directement en ligne, par leur numéro :
- `https://www.formulaires.modernisation.gouv.fr/gf/cerfa_$NUMCERFA.do` : accès en PDF, exemple : [demande de RSA en PDF](https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15481.do).
- `https://www.formulaires.modernisation.gouv.fr/gf/showFormulaireSignaletiqueConsulter.do?numCerfa=$NUMCERFA` : fiche signalétique avec des métadonnées, exemple : [fiche signalétique d'une demande de CMU-C](https://www.formulaires.modernisation.gouv.fr/gf/showFormulaireSignaletiqueConsulter.do?numCerfa=12504).

Voir également [cette discussion](https://forum.etalab.gouv.fr/t/administration-electronique-cerfa-au-format-pdf-tout-le-monde-peut-il-les-lire/344/16) sur le forum Étalab.

**Comment by GautierT** [comment]
Okay. Merci beaucoup !
